### ISSUE TITLE
Tracking issue for Next Release

### ISSUE THREAD

**Issue by rikai** [rikai/Showbot#70]
CC @eriknelson, @s0ph0s-2, @cbojar, @herbmillerjr & @hippyjake as the currently active people working on the project.

This is a tracking bug for the **Next Release** milestone.
The current list of tasks for **Next Release** follows (With the currently assigned people in brackets):

- [ ] [Implement 'silent mode'](https://github.com/rikai/Showbot/issues/64) (@eriknelson)
- [ ] [Track down unknown memory leak](https://github.com/rikai/Showbot/issues/40) (@herbmillerjr & @eriknelson)
- [ ] [Implement command cooldowns using cinch-cooldown]() (@s0ph0s-2)
- [ ] [Implement Rate limiting](https://github.com/rikai/Showbot/issues/63) (Currently noone, mostly needs input and then a simple PR)
- [ ] [Add variable title limits via json.](https://github.com/rikai/Showbot/issues/42) (Currently noone)
- [ ] [Switch Twitter API from polling to streaming](https://github.com/rikai/Showbot/issues/21) (@rikai)
- [x] [Async title page reload](https://github.com/rikai/Showbot/issues/38) (@eriknelson)
- [x] [Abstract Admin functionality](https://github.com/rikai/Showbot/issues/60) (@eriknelson)
- [x] [Make plugins that use data.json more robust](https://github.com/rikai/Showbot/issues/31) (@cbojar)

I've created this as a central place to collaborate on finishing off these tasks in a timely fashion. The original stated goal date of this release was 'Mid-September', with the caveat of possibly taking to the end of September.

If it's still possible to hit that goal, that'd be really nice. However, if outside forces prevent working on stuff, that's understandable as well and stating as much as fine. It'll just let other people take over in your stead. :+1: 

Feel free to use this issue for discussion of collaboration, passing off of information or anything else relating to getting these tasks done.

**Comment by rikai** [comment]
Also, would doing some sort of 'group sprint' this weekend be something that would help people along?

I'm willing to be available via IRC if we wanted to make a group effort! :100:

**Comment by herbmillerjr** [comment]
That kind of thing seems to help the Solus project a lot. I can only take part in such when it's my turn to elder-sit the parental unit (like last weekend, when I started contributing). But whenever it lands on one of those weekends I'm game. Sorry I can't help with one for this release cycle.

**Comment by rikai** [comment]
Due to the lack of responses, i think i'll delay this until next weekend, that way everyone will have a week to plan for it. :+1:

**Comment by rikai** [comment]
@eriknelson, @s0ph0s-2, @cbojar, @herbmillerjr & @hippyjake Any of you guys able to make it at any point between now and sunday? :)

**Comment by s0ph0s-2** [comment]
I have exams this upcoming week, so I might have some time after I finish studying.

**Comment by herbmillerjr** [comment]
Yeah, I should be able to drop in here and there.

**Comment by rikai** [comment]
Alright, just give me a ping if you're active in the IRC and working on something so i can keep track. I'm going to be working on the tweetstream stuff myself this weekend, but i'd be happy to see discussion/activity on any implementation details or whatever over the course of this weekend.

Hoping for a big push to check off the rest of those boxes and release! :+1: :dancer: :meat_on_bone:

**Comment by rikai** [comment]
Sadly, we missed our release date goal due to everyone being extremely busy, but that's understandable.

That said, I'd still like to get things crossed off the list, so if you guys could give me a status update on things when you've got a chance, that'd be wonderful! :meat_on_bone:

**Comment by s0ph0s-2** [comment]
I hope to finish up my issue this weekend, but I can't fully commit to it until I know how much other work I'll have.

**Comment by rikai** [comment]
Initial work on the tweetstream code is now in the [FEATURE/tweetstream branch](https://github.com/rikai/Showbot/tree/FEATURE/tweetstream).

The code is pretty minimal to get it up and running, but I'm running into issues restricting the output to only the users tweets, rather than replies from others and retweets as well.

**Comment by rikai** [comment]
@s0ph0s-2 Had a chance to look at the updated cinch-cooldown?
